<a href="https://colab.research.google.com/github/sadman-02/Lab-Assignment-01/blob/main/SML_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question**-Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
  Run the code twice.

  With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
  
  Without setting a seed, allowing random values to change each time.

In [4]:
import numpy as np

In [7]:
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 50, size=(3, 3))
print("Matrix with seed:\n", matrix_with_seed)


matrix_without_seed = np.random.randint(1, 50, size=(3, 3))

print("\nMatrix without seed:\n", matrix_without_seed)

Matrix with seed:
 [[10 37 16]
 [ 1 29 26]
 [30 49 30]]

Matrix without seed:
 [[ 9 10  1]
 [43 41 37]
 [17 37 48]]


1. **Matrix with Seed** : Our setting of `np.random.seed(10)` ensures that the **Matrix with Seed** remains constant.  
2. **Matrix without Seed** : Since no seed is set, it is always different.  

The basic rule is as follows: Seed = Fixed Random Numbers.  
No Seed = Every time, new random numbers are generated.